### ISSUE TITLE
Bookmarkデータの簡略化

### ISSUE THREAD

**Issue by satakagi** [WhiteHawk-taka/chirimen-setup#4]
いろいろ試してみたところ、最小限で以下のような情報だけでブックマークデータとして認識できることがわかりました。
https://github.com/chirimen-oh/chirimen-raspi3/blob/master/_gc/bookmark/Bookmarks

**Comment by satakagi** [comment]
https://github.com/WhiteHawk-taka/chirimen-setup/blob/7841ef15a8f089feb96fc4f1a9800bf9e9af3e7d/setup.sh#L74
を
`mv /home/pi/_gc/bookmark/Bookmarks /home/pi/.config/chromium/Default/Bookmarks`
でできるようにあちらのリポジトリに追加しました。

**Comment by WhiteHawk-taka** [comment]
本家にコミットが入ったのでcloseします。
https://github.com/chirimen-oh/chirimen-raspi3/commit/155a15bcbac426e2363b831ad9c6b862c847d970
