### ISSUE TITLE
https://github.com/chirimen-oh/chirimen-raspi3/に合流させる

### ISSUE THREAD

**Issue by satakagi** [WhiteHawk-taka/chirimen-setup#5]
https://github.com/chirimen-oh/chirimen-raspi3/issues/31
です。　一応こちらにも記載しておきますね。

**Comment by satakagi** [comment]
現在最新のリリースのraspbianに対して #4 のパッチを施したsetup.shを使い、現在の https://github.com/chirimen-oh/chirimen-raspi3 の登録内容を使ったセットアップを試し、手持ちのデバイスの範囲(GPIOの全チャンネルのInと、いくつかのチャンネルのOut、およびI2C-ADT7410)のテストを行い、この範囲では問題なく動作（ブックマークやLocalウェブページ含）することを確認しました。　https://github.com/chirimen-oh/chirimen-raspi3　へのプルリクエストをお願いします。

**Comment by WhiteHawk-taka** [comment]
合流しました。
https://github.com/chirimen-oh/chirimen-raspi3/pull/39
